config/routes.rb
Rails.application.routes.draw do
  get 'panda_controller/authorize_upload'

  get "/panda/authorize_upload", :to => "panda#authorize_upload"

  root :to => "videos#index"
  devise_for :users
  resources :videos
end

app/models/panda_video.rb
class PandaVideo < ActiveRecord::Base

  validates_presence_of :panda_video_id

  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  video      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :string(255)
#

class Video < ActiveRecord::Base
  belongs_to :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/padnda_videos_controller.rb
class PandaVideosController < ApplicationController
  def show
    @video = PandaVideo.find(params[:id])
    @original_video = @video.panda_video
    @h264e = @original_video.encodings["h264"]
  end

  def new
    @video = PandaVideo.new
  end

  def create
    @video = PandaVideo.create!(params[:video])
    redirect_to :action => :show, :id => @video.id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/panda_controller.rb
class PandaController < ApplicationController

  # def authorize_upload
  #   payload = JSON.parse(params['payload'])

  #   binding.pry

  #   options = {
  #     profiles: "h264,webm",
  #     # payload: 'something',
  #     # path_format: ':video_id/:profile/play',
  #   }
  #   if payload['filename']
  #     url = '/videos/upload.json'
  #     options['file_name'] = payload['filename']
  #     options['file_size'] = payload['filesize']
  #   else
  #     url = "/videos.json"
  #     options['source_url'] = payload['fileurl']
  #   end

  #   upload = Panda.post(url, options)

  #   render :json => {:upload_url => upload['location']}
  # end

  def authorize_upload
    payload = JSON.parse(params['payload'])
    upload = Panda.post('/videos/upload.json', {
      file_name: payload['filename'],
      file_size: payload['filesize'],
      profiles: "h264",
    })

    render :json => {:upload_url => upload['location']}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  protect_from_forgery :except => :create
# before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.pluck 'title'
    @videos = Video.order('created_at DESC')
    respond_to do |format|
      format.html{}
      format.json { render :json => @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all
    @video = @videos.find params[:id]
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # POST /videos
  # POST /videos.json
  def create

    @video = Video.new(video_params)
    file = @video.video.tempfile

    video = Panda::Video.create(:file => file)
    # binding.pry
    video.encodings['h264'].reload

    until video.encodings['h264'].status == 'success'
      video.encodings['h264'].reload
    end

    video.encodings['h264'].encoding_progress
    @video.video = video.encodings['h264'].url

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  # def update
  #   respond_to do |format|
  #     if @video.update(post_params)
  #       format.html { redirect_to @video, notice: 'video was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @video }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @video.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # Rosalind is gay because peter is cool and she is funny looking and if she deletes this then NAOUUU!!!11!!!!1!1!11 ur hed is munted m8e
  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/panda_controller_helper.rb
module PandaControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secondloop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdn.pandastream.com/u/2.3/panda-uploader.min.js"></script>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/pages/index.html.erb
<h1> SECONDS </h1>

app/views/panda_controller/authorize_upload.html.erb
<h1>PandaController#authorize_upload</h1>
<p>Find me in app/views/panda_controller/authorize_upload.html.erb</p>

app/views/pandavideo/show.html.erb
<% if @h264e.status == "success" %>
  <video id="movie" width="<%= @h264e.width %>" height="<%= @h264e.height %>" preload="none"
    poster="<%= @h264e.screenshots.first %>" controls>
    <source src="<%= @h264e.url %>" type="video/mp4">
  </video>
<% else %>
   Your video is processing: <%= @h264e.encoding_progress.to_i %>%
<% end %>

app/views/videos/index.html.erb
<!-- <h1> SECONDS </h1> -->
<!--///// video grid //////-->
<!-- <header>
  <h2>seconds</h2>
</header> -->
<!-- <div id="input">
    <label for="title"></label>
    <input type="text" id="title" placeholder="title" autofocus>


</div> -->
<a href= <%=new_video_path%> class="record" >
<ul>
  <li> RECORD </li>
</ul>
</a>
<div class="about">
<h3>SECONDS</h3>
  Seconds is a small project that takes short 3 second videos using your device's web cam. The results are hilarious. When you're ready, click record, allow access to your camera, give your video a title and hit enter!
  <aside>
     X CLOSE
  </aside>
</div>
<!-- <a id="record" disabled>Stop Recording</button> -->
<div class="videos-container"><div class="grid-video"></div></div>
<div class="socialmedia">
  <a href="https://twitter.com/share" class="twitter-share-button" data-url="https://seconds.herokuapp.com" data-via="rosskinner" data-hashtags="OnlySeconds" data-lang="en">Tweet</a>
  <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fseconds.herokuapp.com&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21&amp;appId=265218853682249" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;width:150px;" allowTransparency="true"></iframe>
</div>
<!-- <div class="sign-in"></div>
<div class="sign-up"></div>
<div class="signin-button">SIGN IN</div>
<div class="signup-button">SIGN UP</div> -->
<script id="videos-template" type="text/handlebars-template">
  <video class="videos" src="{{ video }}" autoplay loop>
  </video>
</script>

<script id="title-template" type="text/handlebars-template">
<h1> {{ title }}</h1>
</script>

<script id="signin-template" type="text/handlebars-template">

  <%= form_tag( new_user_session_path ) do %>
    <div><%= label_tag :email %><br />
    <%= email_field_tag :email, nil, autofocus: true %></div>

    <div><%= label_tag :password %><br />
      <%= password_field_tag :password, nil, autocomplete: "off" %></div>

    <div><%= submit_tag 'Sign In', class: 'submit' %></div>
  <% end %>

  <%= render "users/shared/links" %>

  <div class="close">CLOSE X</div>
</script>

<script id="signup-template" type="text/handlebars-template">
  <h2>Sign up</h2>

<%= form_tag( user_registration_path ) do %>

  <div><%= label_tag :email %><br />
    <%= email_field_tag :email, nil, autofocus: true %></div>

    <div><%= label_tag :password %><br />
      <%= password_field_tag :password, nil, autocomplete: "off" %></div>

  <div><%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation,nil, autocomplete: "off" %></div>

  <div><%= submit_tag 'Sign Up', class: 'submit' %></div>
<% end %>

<%= render "users/shared/links" %>
<div class="close">CLOSE X</div>
</script>

<!-- social media share -->
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/videos/new.html.erb
<div id="input" >
    <input type="text" id="title" class="full-view-input" placeholder="TITLE" autofocus>
</div>
<a href= <%=root_path%> class="record" >
<ul>
  <li> GRID </li>
</ul>
</a>
<!-- <div class="record instruct">
  <p>Give your video a title and press enter to start your 3 second video and wait...</p>
</div> -->
<!-- <button id="stop-recording" disabled></button> -->
<div class=" grid-video videos-container full-view-container "></div>
<div class="countdown"></div>